#!/usr/bin/env bash
# Fetch a Pokemon background from Pokemon-Terminal and wire it into Ghostty.
#
# Pokemon-Terminal doesn't support Ghostty (it drives iTerm2/Kitty-style APIs), so this only borrows
# its artwork and uses Ghostty's native `background-image`. The image is downloaded per machine and
# deliberately not committed (Pokemon artwork isn't ours to redistribute from a public repo).
#
# Usage: scripts/pokemon-bg.sh [deoxys|attack|defense|speed|blaziken|<dex number 1-719>|off]
# The artwork set covers Gen I-VI (#1-719), so newer Pokemon (e.g. Ceruledge, #937) have no image.
set -euo pipefail

REPO="LazoVelko/Pokemon-Terminal"
REF="0fb9b07df35c4757ce3abc6304cfe7b9b3d3e1a5"   # pinned commit
DIR="$HOME/.config/ghostty"
SNIPPET="$DIR/pokemon.ghostty"                    # loaded by `config-file = ?pokemon.ghostty`
FORM="${1:-deoxys}"

# Dex number -> generation folder
gen_dir() {
  local n=$1
  if   (( n <= 151 )); then echo "Generation%20I%20-%20Kanto"
  elif (( n <= 251 )); then echo "Generation%20II%20-%20Johto"
  elif (( n <= 386 )); then echo "Generation%20III%20-%20Hoenn"
  elif (( n <= 493 )); then echo "Generation%20IV%20-%20Sinnoh"
  elif (( n <= 649 )); then echo "Generation%20V%20-%20Unova"
  else                      echo "Generation%20VI%20-%20Kalos"
  fi
}

case "$FORM" in
  off)      rm -f "$SNIPPET" "$DIR/pokemon-bg.jpg"; echo "removed Pokemon background"; exit 0 ;;
  deoxys)   dex=386 ;;
  blaziken) dex=257 ;;
  attack|defense|speed) path="pokemonterminal/Images/Extra/deoxys-$FORM.jpg" ;;
  *[!0-9]*|"") echo "unknown: $FORM" >&2; exit 1 ;;
  *)        dex=$FORM ;;
esac
if [[ -z "${path:-}" ]]; then
  (( dex >= 1 && dex <= 719 )) || { echo "dex number must be 1-719 (art set ends at Gen VI)" >&2; exit 1; }
  path="pokemonterminal/Images/$(gen_dir "$dex")/$dex.jpg"
fi

mkdir -p "$DIR"
curl -fsSL "https://raw.githubusercontent.com/$REPO/$REF/$path" -o "$DIR/pokemon-bg.jpg"
cat > "$SNIPPET" <<CFG
# Generated by scripts/pokemon-bg.sh ($FORM). Not tracked.
background-image = $DIR/pokemon-bg.jpg
background-image-opacity = 0.2
background-image-fit = cover
background-image-position = center
CFG
echo "$FORM installed. Reload Ghostty config (cmd+shift+,) to apply."
